version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++ libsqlite3-dev cmake git'
      - run:
          name: Installing Catch2
          command: 'git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install'
      - run:
          name:
      - run:
          name: Creating Build Files
          command: 'mkdir build && cd build && cmake ..'
      - run:
          name: Creating Binary Files
          command: 'cd build && make'